use_frameworks!

target 'DeveloperKit_Example' do
  pod 'DeveloperKit', :path => '../'
  
#  pod 'DeveloperKit/Clean', :path => '../'

  target 'DeveloperKit_Tests' do
    inherit! :search_paths

    
  end
end
